# Generated by Django 5.0.4 on 2024-05-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='4933', max_length=4)),
                ('base_url', models.URLField(blank=True)),
                ('connected', models.BooleanField(default=False)),
                ('keep_alive_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timelapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=10)),
                ('photos_taken', models.PositiveIntegerField(default=0)),
                ('timelapse_preset_url', models.URLField(default='/gopro/camera/presets/load?id=65536')),
                ('task_id', models.PositiveIntegerField(blank=True)),
                ('gopro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='controller.gopro')),
            ],
        ),
    ]
