# Generated by Django 5.0.4 on 2024-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopro',
            name='identifier',
            field=models.CharField(default='4933', max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
