# Generated by Django 5.0.4 on 2024-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopro',
            name='keep_alive_signal',
            field=models.BooleanField(default=False),
        ),
    ]
