# Generated by Django 5.0.4 on 2024-05-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_gopro_identifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controller',
        ),
    ]
