# Generated by Django 5.0.4 on 2024-05-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_delete_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopro',
            name='keep_alive_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
