# Generated by Django 5.0.4 on 2024-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_gopro_keep_alive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopro',
            name='keep_alive_id',
            field=models.IntegerField(default=-1),
        ),
    ]
