# Generated by Django 5.0.4 on 2024-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_timelapse_timelapse_preset_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField()),
                ('name', models.CharField(max_length=20)),
                ('size', models.FloatField()),
            ],
        ),
    ]
